-- MySQL Script generated by MySQL Workbench
-- 03/20/15 20:02:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`UserType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UserType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UserType` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`type_id`, `type_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(65) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `join_date` DATE NOT NULL,
  `type` INT NOT NULL DEFAULT 0,
  `user_icon` VARCHAR(45) NOT NULL DEFAULT 'default.jpg',
  PRIMARY KEY (`uid`),
  INDEX `user_type_key_idx` (`type` ASC),
  CONSTRAINT `user_type_key`
    FOREIGN KEY (`type`)
    REFERENCES `mydb`.`UserType` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Question` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Question` (
  `qid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `html` LONGBLOB NOT NULL,
  `user` INT NOT NULL,
  `post_date` DATE NOT NULL,
  `edit_date` DATE NULL,
  `Questioncol` VARCHAR(45) NULL,
  PRIMARY KEY (`qid`),
  INDEX `question_user_key_idx` (`user` ASC),
  CONSTRAINT `question_user_key`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`User` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `tag_id` INT NOT NULL,
  `tag_string` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Answer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Answer` (
  `aid` INT NOT NULL AUTO_INCREMENT,
  `html` LONGBLOB NOT NULL,
  `user` INT NOT NULL,
  `question` INT NOT NULL,
  `post_date` DATE NOT NULL,
  `edit_date` DATE NULL,
  PRIMARY KEY (`aid`),
  INDEX `answer_question_key_idx` (`question` ASC),
  INDEX `answer_user_key_idx` (`user` ASC),
  CONSTRAINT `answer_question_key`
    FOREIGN KEY (`question`)
    REFERENCES `mydb`.`Question` (`qid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `answer_user_key`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`User` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QuestionComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QuestionComment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`QuestionComment` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(250) NOT NULL,
  `user` INT NOT NULL,
  `post_date` DATE NOT NULL,
  `edit_date` DATE NULL,
  `question` INT NOT NULL,
  PRIMARY KEY (`cid`),
  INDEX `a_comment_user_key_idx` (`user` ASC),
  INDEX `a_comment_question_key_idx` (`question` ASC),
  CONSTRAINT `q_comment_user_key`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`User` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `q_comment_question_key`
    FOREIGN KEY (`question`)
    REFERENCES `mydb`.`Question` (`qid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AnswerComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AnswerComment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AnswerComment` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(250) NOT NULL,
  `user` INT NOT NULL,
  `post_date` DATE NOT NULL,
  `edit_date` DATE NULL,
  `answer` INT NULL,
  PRIMARY KEY (`cid`),
  INDEX `a_comment_user_key_idx` (`user` ASC),
  INDEX `a_comment_answer_key_idx` (`answer` ASC),
  CONSTRAINT `a_comment_user_key`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`User` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `a_comment_answer_key`
    FOREIGN KEY (`answer`)
    REFERENCES `mydb`.`Answer` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QuestionTags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QuestionTags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`QuestionTags` (
  `question` INT NOT NULL,
  `tag` INT NOT NULL,
  PRIMARY KEY (`question`, `tag`),
  INDEX `question_tags_t_key_idx` (`tag` ASC),
  CONSTRAINT `question_tags_q_key`
    FOREIGN KEY (`question`)
    REFERENCES `mydb`.`Question` (`qid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `question_tags_t_key`
    FOREIGN KEY (`tag`)
    REFERENCES `mydb`.`Tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QuestionScore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QuestionScore` ;

CREATE TABLE IF NOT EXISTS `mydb`.`QuestionScore` (
  `qid` INT NOT NULL,
  `uid` INT NOT NULL,
  `vote` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`qid`, `uid`),
  INDEX `qscore_user_key_idx` (`uid` ASC),
  CONSTRAINT `qscore_question_key`
    FOREIGN KEY (`qid`)
    REFERENCES `mydb`.`Question` (`qid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `qscore_user_key`
    FOREIGN KEY (`uid`)
    REFERENCES `mydb`.`User` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QCommentScore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QCommentScore` ;

CREATE TABLE IF NOT EXISTS `mydb`.`QCommentScore` (
  `cid` INT NOT NULL,
  `uid` INT NOT NULL,
  `vote` INT NOT NULL,
  PRIMARY KEY (`cid`, `uid`),
  INDEX `qcomment_user_key_idx` (`uid` ASC),
  CONSTRAINT `qcomment_comment_key`
    FOREIGN KEY (`cid`)
    REFERENCES `mydb`.`QuestionComment` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `qcomment_user_key`
    FOREIGN KEY (`uid`)
    REFERENCES `mydb`.`User` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ACommentScore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ACommentScore` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ACommentScore` (
  `cid` INT NOT NULL,
  `uid` INT NOT NULL,
  `vote` INT NOT NULL,
  PRIMARY KEY (`cid`, `uid`),
  INDEX `ascore_user_id_idx` (`uid` ASC),
  CONSTRAINT `ascore_comment_id`
    FOREIGN KEY (`cid`)
    REFERENCES `mydb`.`AnswerComment` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ascore_user_id`
    FOREIGN KEY (`uid`)
    REFERENCES `mydb`.`User` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AnswerScore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AnswerScore` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AnswerScore` (
  `aid` INT NOT NULL,
  `uid` INT NOT NULL,
  `vote` INT NOT NULL,
  PRIMARY KEY (`aid`, `uid`),
  INDEX `ascore_user_uid_idx` (`uid` ASC),
  CONSTRAINT `ascore_answer_aid`
    FOREIGN KEY (`aid`)
    REFERENCES `mydb`.`Answer` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ascore_user_uid`
    FOREIGN KEY (`uid`)
    REFERENCES `mydb`.`User` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -------------------------------------------------------
-- Insert user types
-- -------------------------------------------------------

insert into UserType (type_name) values ('Admin');
insert into UserType (type_name) values ('User');
